[package]
name = "dockerize-rust"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "dockerize_rust"
path = "src/main.rs"

[dependencies]
dotenv = "0.15.0"
hyper = { version = "0.14.27", features = ["full"] }
tokio = { version = "1.29.1", features = ["full"] }